// ─────────────────────────────────────────────
// One-off migration (2026-09-25): redraw the 21 community reference
// templates as EXACT rectangles at their own W × H.
//
// They shared one rounded-rectangle outline drawn in a square box and
// stretched to each size, which turned the corners into ovals and broke the
// rule that a pattern's W × H always has its outline's exact proportions.
// The new outline is generated by the app's own geometry code (rectSegs +
// serializePath), identical to the seed data in patternStore.
//
// Safe by construction:
//   • only docs whose svgPath is still the old shared outline are touched
//     (an admin-edited template is left alone and reported);
//   • width/height are not changed;
//   • dry run by default — pass --apply to write.
//
// Run: node --experimental-strip-types --env-file=.env scripts/migrate-reference-templates-exact.mts [--apply]
// Also reports user-library patterns whose size doesn't match their outline
// (read-only — those are fixed by their owners; the app blocks them).
// ─────────────────────────────────────────────
import { createRequire } from "node:module";
import { rectSegs, serializePath, sizeMatchesOutline } from "../src/lib/utils/pathGeometry.ts";

const require = createRequire(import.meta.url);
const { cert, initializeApp } = require("firebase-admin/app");
const { getFirestore, FieldValue } = require("firebase-admin/firestore");

const OLD_OUTLINE = "M4,4 L96,4 Q98,4 98,6 L98,94 Q98,96 96,96 L4,96 Q2,96 2,94 L2,6 Q2,4 4,4 Z";
const APPLY = process.argv.includes("--apply");

initializeApp({ credential: cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON!)) });
const db = getFirestore();

const snap = await db.collection("patterns").get();
const toFix: Array<{ id: string; name: string; w: number; h: number; next: string }> = [];
const skipped: string[] = [];
for (const doc of snap.docs) {
	const p = doc.data();
	if (!doc.id.startsWith("comm-")) continue;
	if (p.svgPath !== OLD_OUTLINE) { skipped.push(`${doc.id} (outline already changed — left alone)`); continue; }
	const next = serializePath(rectSegs(0, 0, p.widthInches, p.heightInches));
	if (!sizeMatchesOutline(next, p.widthInches, p.heightInches)) throw new Error(`Generated outline doesn't match size for ${doc.id}`);
	toFix.push({ id: doc.id, name: p.name, w: p.widthInches, h: p.heightInches, next });
}

console.log(`${APPLY ? "APPLYING" : "DRY RUN"} — ${toFix.length} template(s) to redraw as exact rectangles`);
for (const t of toFix) console.log(`  ${t.id}  ${t.w} x ${t.h}  →  ${t.next}   (${t.name})`);
for (const s of skipped) console.log(`  skipped: ${s}`);

if (APPLY && toFix.length) {
	const batch = db.batch();
	for (const t of toFix) batch.update(db.collection("patterns").doc(t.id), { svgPath: t.next, updatedAt: FieldValue.serverTimestamp() });
	await batch.commit();
	console.log(`Wrote ${toFix.length} document(s).`);
}

// Read-only report: every live pattern and user pattern whose size doesn't match its outline.
const users = await db.collection("userPatterns").get();
const bad: string[] = [];
for (const doc of [...snap.docs, ...users.docs]) {
	const p = doc.data();
	const fixed = toFix.find((t) => t.id === doc.id);
	const path = APPLY && fixed ? fixed.next : p.svgPath;
	let ok = false;
	try { ok = sizeMatchesOutline(path, p.widthInches, p.heightInches); } catch { ok = false; }
	if (!ok) bad.push(`${doc.ref.parent.id}/${doc.id}  "${p.name}"  ${p.widthInches} x ${p.heightInches}${fixed && !APPLY ? "  (fixed by --apply)" : ""}`);
}
console.log(`\nSize-vs-outline mismatches (${bad.length}):`);
for (const b of bad) console.log(`  ${b}`);
